In [3]:
"""
Problem: Arrays
Platform: HackerRank
Difficulty: Easy
Concepts: NumPy Arrays, Array Slicing, Type Conversion

Problem Link:
https://www.hackerrank.com/challenges/np-arrays/problem
"""
import numpy

def arrays(arr):
    s=numpy.array(arr,float)
    rev=s[::-1]
    return rev
arr = input().strip().split(' ')
result = arrays(arr)
print(result)

 5 4 3


[3. 4. 5.]


In [9]:
"""
Problem: Transpose and Flatten
Platform: HackerRank
Difficulty: Easy
Concepts: NumPy Arrays, transpose(), flatten()

Problem Link:
https://www.hackerrank.com/challenges/np-transpose-and-flatten/problem
"""
import numpy
dim = input().strip()
n=dim[0]
m=dim[2]
arr=[]
for i in range(int(n)):
    a=input().strip().split()
    arr.append(a)
int_arr=numpy.array(arr,numpy.int64)
print("array-")
print(int_arr)
print("transpose array-")
print(numpy.transpose(int_arr))
print("flatten array-")
print(int_arr.flatten())

 2 2
 1 2
 3 4


array-
[[1 2]
 [3 4]]
transpose array-
[[1 3]
 [2 4]]
flatten array-
[1 2 3 4]
