In [2]:
#creation of numpy array and its properties

In [1]:
import numpy as np

In [4]:
arr=np.array([1,2,3,4])
print(arr , type(arr) , arr.dtype) #all will be numners

arr2=np.array([1,2,3,4,"sanchali"])
print(arr2 , type(arr2) ,arr2.dtype) # all are strings because numpy arrays are homogenous

[1 2 3 4] <class 'numpy.ndarray'> int64
['1' '2' '3' '4' 'sanchali'] <class 'numpy.ndarray'> <U21


In [5]:
arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]]) # 2D array
print(arr2D , arr2D.shape) # now showing the dimension of the array

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [23]:
#create from scratch
arr3=np.zeros((2,3),dtype="int64") #prefill with 0
print(arr3 , arr3.shape)

arr4=np.ones((3,3),dtype="int64") #prefill with 1
print(arr4)

arr5=np.ones((5,),dtype="int64") #1D array
print(arr5)

arr6=np.full((3,4),5) #all the elements will be 5
print(arr6)

arr7=np.eye(3) #identity matrix
print(arr7)

arr8=np.arange(1,10,2) #1D array with elements in range of 1 to 10
print(arr8)

arr9=np.linspace(1,100,4) #evenly spaced array
print(arr9)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[1 1 1 1 1]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1 3 5 7 9]
[  1.  34.  67. 100.]


In [6]:
# Some more properties of array
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr.shape) #prints the dimension = m x n
print(arr.size) #number of elements
print(arr.dtype) #prints the data type of the elements
print(arr.ndim) #print number of dimensions - 2D

float_arr=arr.astype(np.float64) #to convert the data type (typecasting) of an existing array
print(float_arr , float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [8]:
#operations on array
arr=np.array([[1,2,3],[4,5,6]])
reshaped=arr.reshape((3,2)) # reshaping of array
print(arr,arr.shape)
print(reshaped,reshaped.shape)

flattened=arr.flatten() #converts 2d array into 1D array
print(flattened)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6]


In [12]:
#indexing
arr1=np.array(['sanchali','saha','RCCIIT','Nalta'])
print(arr1[2]) # for 1D
idx=[0,1,3] 
print(arr1[idx]) #fancy indexing for accessing multiple elements
arr2=np.array([[1,2,3],[4,5,6]]) #for 2D
print(arr2[1][2])

RCCIIT
['sanchali' 'saha' 'Nalta']
6


In [16]:
#boolean indexing
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[arr>2]) #gives elements greater than 2
print(arr[arr%2==0]) #gives even elements
print(arr[arr%2!=0]) #gives odd elements

[3 4 5 6 7 8 9]
[2 4 6 8]
[1 3 5 7 9]


In [20]:
#slicing
arr=np.array([1,2,3,4,5,6])
print(arr[1:4]) #[start,end,step]
print(arr[1:])
print(arr[:4])
print(arr[: :2])

[2 3 4]
[2 3 4 5 6]
[1 2 3 4]
[1 3 5]


In [24]:
#complex number
arr1=np.array([3+2j]) #j = imaginary number
arr2=np.array([6+1j])
print(arr1 + arr2)
print(arr2 - arr1)

[9.+3.j]
[3.-1.j]


In [8]:
#multi-demensional arrays

arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)
print(np.sum(arr2D)) #sum of all arrays

sum_of_all_col=np.sum(arr2D,axis=0) #sum of all columns, axis 0 because we want row's 1st elements
print(sum_of_all_col)

sum_of_all_rows=np.sum(arr2D,axis=1)
print(sum_of_all_rows)

#slicing
print(arr2D[0:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [15]:
#3D array
arr3D=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]]) #2 x 3 x 2
print(arr3D,arr3D.shape)

#indexing
print(arr3D[1,1,0])

#slicing
print("only the 1st layer's 0th row and 0 to 1 column-")
print(arr3D[0,0,0:2]) 
print("first row from both layers-")
print(arr3D[:,0,:]) 
print("first cloumn from both layers-")
print(arr3D[:,:,0]) 
print("replace first row from both layers with 99-")
arr3D[:,0,:]=99
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
9
only the 1st layer's 0th row and 0 to 1 column-
[1 2]
first row from both layers-
[[1 2]
 [7 8]]
first cloumn from both layers-
[[ 1  3  5]
 [ 7  9 11]]
replace first row from both layers with 99-
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [16]:
#vectorizastion
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print(arr1**2)
print(arr1+2)
print(arr1+arr2)

[ 1  4  9 16 25]
[3 4 5 6 7]
[ 7  9 11 13 15]


In [18]:
#broadcasting
arr1=np.array([1,2,3,4,5])
arr2=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr1.shape) #(5,)==> 1 x 5
print(arr2.shape) #(2, 5)
#1 x 5 and 2 x 5 are compatible
print(arr1+arr2)

(5,)
(2, 5)
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [25]:
#normalization
arr=np.array([1,2,3,4])
mean=np.mean(arr)
std_dev=np.std(arr) #standard deviation
normalized_arr=(arr-mean)/std_dev
print(normalized_arr)

[-1.34164079 -0.4472136   0.4472136   1.34164079]


In [30]:
#mathematical functions
#aggrigation functions

arr=np.array([1,2,3,4,5])
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))

15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0


In [31]:
arr=np.array([1,2,3,4,5])
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,3))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [35]:
#log
arr=np.array([1,2,3,4,5])
print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [44]:
#rounding
print(np.round(3.14))
print(np.ceil(3.14))
print(np.floor(3.14))
print(np.trunc(5.65))
arr=np.array([1,-2,3,3,2,4,-1])
print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr))

3.0
4.0
3.0
5.0
[-2 -1  1  2  3  4]
[-2 -1  1  2  3  3  4]
[1 2 3 3 2 4 1]
