In [2]:
#creation of numpy array and its properties

In [2]:
import numpy as np

In [4]:
arr=np.array([1,2,3,4])
print(arr , type(arr) , arr.dtype) #all will be numners

arr2=np.array([1,2,3,4,"sanchali"])
print(arr2 , type(arr2) ,arr2.dtype) # all are strings because numpy arrays are homogenous

[1 2 3 4] <class 'numpy.ndarray'> int64
['1' '2' '3' '4' 'sanchali'] <class 'numpy.ndarray'> <U21


In [5]:
arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]]) # 2D array
print(arr2D , arr2D.shape) # now showing the dimension of the array

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [23]:
#create from scratch
arr3=np.zeros((2,3),dtype="int64") #prefill with 0
print(arr3 , arr3.shape)

arr4=np.ones((3,3),dtype="int64") #prefill with 1
print(arr4)

arr5=np.ones((5,),dtype="int64") #1D array
print(arr5)

arr6=np.full((3,4),5) #all the elements will be 5
print(arr6)

arr7=np.eye(3) #identity matrix
print(arr7)

arr8=np.arange(1,10,2) #1D array with elements in range of 1 to 10
print(arr8)

arr9=np.linspace(1,100,4) #evenly spaced array
print(arr9)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[1 1 1 1 1]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1 3 5 7 9]
[  1.  34.  67. 100.]


In [6]:
# Some more properties of array
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr.shape) #prints the dimension = m x n
print(arr.size) #number of elements
print(arr.dtype) #prints the data type of the elements
print(arr.ndim) #print number of dimensions - 2D

float_arr=arr.astype(np.float64) #to convert the data type (typecasting) of an existing array
print(float_arr , float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [8]:
#operations on array
arr=np.array([[1,2,3],[4,5,6]])
reshaped=arr.reshape((3,2)) # reshaping of array
print(arr,arr.shape)
print(reshaped,reshaped.shape)

flattened=arr.flatten() #converts 2d array into 1D array
print(flattened)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6]


In [12]:
#indexing
arr1=np.array(['sanchali','saha','RCCIIT','Nalta'])
print(arr1[2]) # for 1D
idx=[0,1,3] 
print(arr1[idx]) #fancy indexing for accessing multiple elements
arr2=np.array([[1,2,3],[4,5,6]]) #for 2D
print(arr2[1][2])

RCCIIT
['sanchali' 'saha' 'Nalta']
6


In [16]:
#boolean indexing
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[arr>2]) #gives elements greater than 2
print(arr[arr%2==0]) #gives even elements
print(arr[arr%2!=0]) #gives odd elements

[3 4 5 6 7 8 9]
[2 4 6 8]
[1 3 5 7 9]
