In [1]:
#creation of numpy array and its properties

In [2]:
import numpy as np

In [5]:
arr=np.array([1,2,3,4])
print(arr , type(arr) , arr.dtype) #all will be numners

arr2=np.array([1,2,3,4,"sanchali"])
print(arr2 , type(arr2) ,arr2.dtype) # all are strings because numpy arrays are homogenous

[1 2 3 4] <class 'numpy.ndarray'> int64
['1' '2' '3' '4' 'sanchali'] <class 'numpy.ndarray'> <U21


In [8]:
arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]]) # 2D array
print(arr2D , arr2D.shape) # now showing the dimension of the array

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)
